[profile.default]
  auto_detect_solc = false
  bytecode_hash = "ipfs"
  evm_version = "shanghai" # needed for greater coverage of EVM chains
  fs_permissions = [
    { access = "read", path = "./out-optimized" },
    { access = "read", path = "package.json" },
  ]
  gas_limit = 9223372036854775807
  gas_reports = ["SablierStakingMock"]
  optimizer = true
  optimizer_runs = 10_000_000
  out = "out"
  script = "scripts/solidity"
  sender = "0x1804c8AB1F12E6bbf3894d4083f33e07309d1f38"
  solc = "0.8.29"
  src = "src"
  test = "tests"

[profile.default.fuzz]
  max_test_rejects = 1_000_000 # Number of times `vm.assume` can fail
  runs = 100

[profile.default.invariant]
  call_override = false # Override unsafe external calls to perform reentrancy checks
  depth = 10            # Number of calls executed in one run
  fail_on_revert = true
  runs = 20
  show_metrics = false

# Speed up compilation and tests during development
[profile.lite]
  optimizer = false

# Compile only the production code and the test mocks with via IR
[profile.optimized]
  out = "out-optimized"
  test = "tests/mocks"
  via_ir = true

# Test the optimized contracts without re-compiling them
[profile.test-optimized]
  src = "tests"

[doc]
  ignore = ["**/*.t.sol"]
  out = "docs"
  repository = "https://github.com/sablier-labs/staking"

[etherscan]
  etherscan = { key = "${ETHERSCAN_API_KEY}" }

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true

[lint]
  lint_on_build = false

[rpc_endpoints]
  # mainnets
  abstract = "https://direct.routeme.sh/rpc/2741/${ROUTEMESH_API_KEY}"
  arbitrum = "https://direct.routeme.sh/rpc/42161/${ROUTEMESH_API_KEY}"
  avalanche = "https://direct.routeme.sh/rpc/43114/${ROUTEMESH_API_KEY}"
  base = "https://direct.routeme.sh/rpc/8453/${ROUTEMESH_API_KEY}"
  berachain = "https://direct.routeme.sh/rpc/80094/${ROUTEMESH_API_KEY}"
  blast = "https://direct.routeme.sh/rpc/81457/${ROUTEMESH_API_KEY}"
  bsc = "https://direct.routeme.sh/rpc/56/${ROUTEMESH_API_KEY}"
  chiliz = "https://direct.routeme.sh/rpc/88888/${ROUTEMESH_API_KEY}"
  core_dao = "https://direct.routeme.sh/rpc/1116/${ROUTEMESH_API_KEY}"
  ethereum = "https://direct.routeme.sh/rpc/1/${ROUTEMESH_API_KEY}"
  gnosis = "https://direct.routeme.sh/rpc/100/${ROUTEMESH_API_KEY}"
  hyperevm = "https://direct.routeme.sh/rpc/999/${ROUTEMESH_API_KEY}"
  lightlink = "https://replicator.phoenix.lightlink.io/rpc/v1"
  linea = "https://direct.routeme.sh/rpc/59144/${ROUTEMESH_API_KEY}"
  mode = "https://direct.routeme.sh/rpc/34443/${ROUTEMESH_API_KEY}"
  morph = "https://rpc.morphl2.io"
  optimism = "https://direct.routeme.sh/rpc/10/${ROUTEMESH_API_KEY}"
  polygon = "https://direct.routeme.sh/rpc/137/${ROUTEMESH_API_KEY}"
  scroll = "https://direct.routeme.sh/rpc/534352/${ROUTEMESH_API_KEY}"
  sei = "https://direct.routeme.sh/rpc/1329/${ROUTEMESH_API_KEY}"
  sonic = "https://direct.routeme.sh/rpc/146/${ROUTEMESH_API_KEY}"
  sophon = "https://direct.routeme.sh/rpc/50104/${ROUTEMESH_API_KEY}"
  superseed = "https://direct.routeme.sh/rpc/5330/${ROUTEMESH_API_KEY}"
  tangle = "https://direct.routeme.sh/rpc/5845/${ROUTEMESH_API_KEY}"
  unichain = "https://direct.routeme.sh/rpc/130/${ROUTEMESH_API_KEY}"
  xdc = "https://direct.routeme.sh/rpc/50/${ROUTEMESH_API_KEY}"
  zksync = "https://direct.routeme.sh/rpc/324/${ROUTEMESH_API_KEY}"
  # testnets
  arbitrum_sepolia = "https://sepolia-rollup.arbitrum.io/rpc"
  base_sepolia = "https://sepolia.base.org"
  mode_sepolia = "https://sepolia.mode.network/"
  optimism_sepolia = "https://sepolia.optimism.io"
  sepolia = "https://direct.routeme.sh/rpc/11155111/${ROUTEMESH_API_KEY}"
